server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
# 注解说明：
#profis.active:配置文件的获取方式
#cloud.config.server.search-locations:本地配置文件的存放路径